---
title: "Mode of delivery and postpartum positive dimensions of well-being"
author: "Laura Giuntoli"
date: "14 marzo 2017"
output: html_document
---
# Mode of delivery and postpartum positive dimensions of well-being

### Background
Psychological outcomes of mode of delivery were mainly studied in terms of depressive symptoms. Many of the studies lack information on positive dimensions of well-being such as life satisfaction, positive affect and flourishing. The aim of the present study was to compare the psychological outcomes of women after emergency Cesarean section (ECS), planned Cesarean section (PCS), instrumental vaginal delivery (IVD), medicalized vaginal delivery (MVD) and spontaneous vaginal delivery (SVD).

###Methods
In this cross-sectional study 102 Italian mothers between 1 and 3 months postpartum completed self-administered measures both on the positive and negative dimensions of well-being. A series of one-way ANOVAs with planned contrasts assessed the mode of delivery (ECS, PCS, IVD, MVD and SVD) differences on Flourishing Scale (FS), Satisfaction With Life Scale (SWLS), Scale of Positive and Negative Experience (SPANE), Beck Depression Inventory-II (BDI-II) and Edinburgh Postnatal Depression Scale (EPDS) scores.

###Findings
Results showed that there was a significant effect of mode of delivery on the FS (F(4,97)=3.42, p=.01), SWLS, (F(4,97)=3.98, p<.01), SPANE-P (F(4,97)=3.67, p<.01) and SPANE-N (F(4,97)=3.95, p<.01) scores. No significant differences were found on the BDI-II and EPDS scores.


###Discussion
Results emphasize the important role of positive dimensions of well-being in discriminating psychological outcomes of delivery mode. Indeed, ECS and IVD are associated to lower scores on well-being dimensions compared to PCS, MVD and SVD. No differences between mode of delivery were found on depressive symptoms scores suggesting that well-being measures are more sensitive in detecting postpartum psychological distress.
